---
default_flow:
  download_dir_tag: /downloads
movies_flow:
  download_dir_tag: /movies
transmission:
  url: localhost
  port: 9091
  username: transmission
  password: password
sftp:
  url: localhost
  port: 22
  username: sftp
  key_path: /root/.ssh/id_rsa
  remote_dir: /home/user
home_assistant:
  url: localhost
  token: ''
  htpc_switch: plex_node